# Generated by Django 3.2.5 on 2022-08-26 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 26, 7, 35, 55, 367645)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 26, 7, 36, 5, 635)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
